### ISSUE TITLE
[BUG] Network error alert when scanning qr image in process of enrolling mobile device

### ISSUE THREAD

**Issue by sshahcodes** [seknox/trasa#130]
**Describe the bug:**

Received Network error (refer to image below) while trying to enroll mobile device.

**Log file / Code snippet / Screenshots:**

![Screenshot_20201028-211105](https://user-images.githubusercontent.com/10177602/97461414-d9b76c00-1965-11eb-83bb-cea9f45d0d53.png)

**Scope of issue:**

- [ ] TRASA codebase
- [ ] dashboard
- [ ] server
- [x] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
Latest trasa mobile app on android

**Comment by PrzemekSkw** [comment]
Hello, I have the same situation.
