### ISSUE TITLE
[BUG] QR image is incompatible with other mobile authenticator app. 

### ISSUE THREAD

**Issue by sshahcodes** [seknox/trasa#177]
**Describe the bug:**
QR image to enroll mobile device is incompatible with other authenticator apps. 

**Expected behavior:**
This prevents using other authenticator apps like (google authenticator, Microsoft authenticator) with TRASA

**Scope of issue:**

- [ ] TRASA codebase
- [x] dashboard
- [x] server
- [x] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
All versions.

**Comment by bhrg3se** [comment]
I think we should store device details in Redis temporarily and store it in the database only when the user enters the correct TOTP code.

**Comment by bhrg3se** [comment]
The flow will be something like this:


**Dashboard**:
- Prompt trasaid/pass in dashboard.
- Send trasaid/pass to server and get `deviceID`,`totpSec`
- Let the user scan the QR code
- Prompt TOTP code from the user, 
	- Send the TOTP code to the server with `deviceID`


**Server**:
- Validate trasaid/pass
- Generate `deviceID`,`totpSec`
- Store struct of device to be created in redis. {`deviceID`,`totpSec`}
- Send request to the cloud server
    - On response from the cloud server, update `fcmToken`,`deviceHygiene` and `publicKey` of struct stored in redis

- Receive TOTP code (with deviceID) from dashboard(browser).
- Use the deviceID to get device struct->totpSec from redis.
- Validate TOTP code, 
	- if correct save the device struct to database



**Mobile App**:
Check query param to distinguish between TRASA and other services. eg (type=private)
	if type==private, get deviceID and send FCM token, public key to cloud proxy
	else, just save the totpSec

**Comment by sshahcodes** [comment]
Since we will be validating TOTP and storing device detail in redis, can we also allow user to directly login after TOTP validation? we can use hTFA flow for totop validation. User will not require to re-enter credential, perform tfa again.
