### ISSUE TITLE
[BUG] assigned privilege list gets messed up while using search in /my page 

### ISSUE THREAD

**Issue by bhrg3se** [seknox/trasa#20]
**Describe the bug:**
Assign multiple services to a user with different privilege (say service A and B ). Then go to /my page and search for a service  B. The privilege(username) list of service B will be replaced by that of A.
 

**Expected behavior:**

The privilege list should be correct.

**Log file / Code snippet / Screenshots:**

The service "local" is assigned with privilege "bhrg3se" and the service "do-beta-test" is assigned with "root"
<img width="1055" alt="Screen Shot 2020-08-22 at 11 36 24 AM" src="https://user-images.githubusercontent.com/10883400/90949973-3762a000-e46d-11ea-8d72-0cd74b14da41.png">

when you search for "local", the privilege of "do-beta-test" replaces that of "local"
<img width="1057" alt="Screen Shot 2020-08-22 at 11 36 39 AM" src="https://user-images.githubusercontent.com/10883400/90949963-2ca80b00-e46d-11ea-9644-f14ac92ddd64.png">

**Scope of issue:**

- [ ] TRASA codebase
- [x] dashboard
- [ ] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
 - TRASA version : master
 - OS (in which TRASA is installed): ubuntu

**Comment by sshahcodes** [comment]
fixed by https://github.com/seknox/trasa/commit/d513ae97c3c5e8319c26487e7b502fc5dab5a7a1

**Comment by sshahcodes** [comment]
fized by https://github.com/seknox/trasa/commit/d513ae97c3c5e8319c26487e7b502fc5dab5a7a1
