### ISSUE TITLE
[BUG] TRASA browser extension stuck

### ISSUE THREAD

**Issue by dagid4** [seknox/trasa#224]
**Describe the bug:**

TRASA browser extension stuck at "Register your browser" and processing without ever end (I have tried 12 hours). Even when I input bad hostname or not existing user, it is somehow processing and never ends.

**Expected behavior:**

It should complete as in the tutorial video.

**Log file / Code snippet / Screenshots:**

![Screenshot_320](https://user-images.githubusercontent.com/22964985/102197615-ab640080-3ec1-11eb-9a38-8c69c1a1734f.png)

**Scope of issue:**

- [ ] TRASA codebase
- [ ] dashboard
- [ ] server
- [ ] mobile app
- [x] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
Firefox Browser 83.0 (64-bit)
TRASA browser extension v1.0

**Comment by sshahcodes** [comment]
Hi, can you confirm that your workstation OS is windows and that you have installed trasa workstation agent as mentioned here - https://www.trasa.io/docs/device-trust/install-trasa-device-agent ?

I suspect you have not installed workstation agent. Do note that only windows installer is supported at this time. For debian, you can reference this guide - https://github.com/seknox/trasa/tree/master/workstation. Other OS setup should be similar...

**Comment by dagid4** [comment]
Hello, I can confirm that used workstation OS is windows. But I didn't know that workstation agent must be used. This could be the problem.

Maybe add a note about the need of the agent installed and used for extension to work in docs.

Thank you for your help, I think you can close the issue.
