### ISSUE TITLE
How to make the data persistent

### ISSUE THREAD

**Issue by inventorematto** [seknox/trasa#273]
Hello everyone!!!
I was looking for a project like this since a year!
Than here you're.
I would like to set up a semi-permanent solution for my remote access needs, and i use for all my 
project the docker compose v2 standard managed by portainer.

Here what i've done until now...

version: '2'
services:
    db:
        container_name: db
        networks:
            trasa:
        environment:
            - POSTGRES_PASSWORD=trasauser
            - POSTGRES_USER=trasauser
            - POSTGRES_DB=trasadb
        image: 'postgres:13.0'
    redis:
        container_name: redis
        image: 'redis:6.0.8'
        networks:
            trasa:
    guacd:
        container_name: guacd
        volumes:
            - '/mnt/DockerData/accessproxy/guac:/tmp/trasa/accessproxy/guac'
        networks:
            trasa:
        image: 'seknox/guacd:v0.0.1'
    trasa:
        links:
            - 'db:db'
            - 'guacd:guacd'
            - 'redis:redis'
        container_name: trasa_app
        volumes:
            - '/mnt/DockerData/accessproxy/guac:/tmp/trasa/accessproxy/guac'
        image: 'seknox/trasa:v1.1.4'
        environment:
            TRASA.LISTENADDR: my.domain.xx
            TRASA.AUTOCERT: 'false'
        networks:
            trasa:        
            dmz:   
networks:
    dmz:
        external:
            name: dmz
    trasa:
        internal:
            name: trasa

My main goal is to have everithing (db, redis, config etc...) in "/mnt/DockerData/accessproxy/" path.
Can someone help me with this????
Thanks in advance,
inventorematto

**Comment by bhrg3se** [comment]
My guess is you want to make all the data persistent.
If that's the case, you might want to add following volumes.
- ` /mnt/DockerData/trasa/db:/var/lib/postgresql/data` in postgres container  
- `/mnt/DockerData/trasa/redis:/data` in redis container
- `/mnt/DockerData/trasa/config/:/etc/trasa` in trasa container
- `/mnt/DockerData/trasa/sessions:/var/trasa/sessions` in trasa container

I've replaced "accessproxy" with "trasa" if that's all right.

**Comment by inventorematto** [comment]
Thanks dude!
