### ISSUE TITLE
[PERF]remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by nanoponge** [seknox/trasa#278]
**Describe the issue/idea:**
When I Open TRASA_HOST in my browser, "remote error: tls: unknown certificate" appeared on the terminal and the page couldn't be opened. How can I solve it? Thank you.

**Scope of the issue/idea:**
dashboard  server

**Comment by bhrg3se** [comment]
@nanoponge Are you hosting TRASA publicly (with autocert enabled) or  in a private network?

**Comment by nanoponge** [comment]
> @nanoponge Are you hosting TRASA publicly (with autocert enabled) or in a private network?

A private network. I set trasa.listenAddr = 127.0.0.1 , and trasa.autoCert=false

**Comment by bhrg3se** [comment]
TRASA will generate self signed certificate by default at `/etc/trasa/certs/trasa-server.crt` and `/etc/trasa/certs/trasa-server.key`.  You can keep using this by ignoring the warning in browser. Or you can replace the certificate and key with your own certificate.

**Comment by bhrg3se** [comment]
What do you mean by "the page couldn't be opened" ?
Is there a warning?
Can you send me the screenshot?

**Comment by nanoponge** [comment]
> What do you mean by "the page couldn't be opened" ?
> Is there a warning?
> Can you send me the screenshot?

![1](https://user-images.githubusercontent.com/47075318/112945962-8d1bcb00-9167-11eb-82d6-d89e9219cea6.png)
![2](https://user-images.githubusercontent.com/47075318/112945969-8ee58e80-9167-11eb-9e29-e6e2e83f435e.png)
I cant't open the TRASA dashboard.

**Comment by bhrg3se** [comment]
Have you tried it in private window?

**Comment by nanoponge** [comment]
Sorry，I can't understand what is ‘private window’ you mean. I run it all in localhost.

**Comment by bhrg3se** [comment]
I meant in incognito window

**Comment by nanoponge** [comment]
I install libssl-dev and re-install trasa, the login page can be opened.
