### ISSUE TITLE
[BUG] RDP not working

### ISSUE THREAD

**Issue by jsisaev1** [seknox/trasa#279]
**Describe the bug:**

I'm trying to connect to rdp session
**Expected behavior:**

Accessing to RDP session 
**Log file / Code snippet / Screenshots:**

In Browser I got timeout error:
Connection to guacd timed out., read tcp 172.17.0.5:44780->172.17.0.4:4822: i/o timeout

In Docker guacd logs I see this:
guacd[7]: INFO:	Creating new client for protocol "rdp"
guacd[7]: INFO:	Connection ID is "$40ad6bf0-bdeb-4f37-93e3-c8e0e29e0fa0"
guacd[59]: ERROR:	Handshake failed, "connect" instruction was not received.
guacd[59]: INFO:	Last user of connection "$40ad6bf0-bdeb-4f37-93e3-c8e0e29e0fa0" disconnected
guacd[7]: INFO:	Connection "$40ad6bf0-bdeb-4f37-93e3-c8e0e29e0fa0" removed.
**Scope of issue:**

- [x] TRASA codebase
- [ ] dashboard
- [x] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
 - TRASA version 1.4.4
 - OS (in which TRASA is installed): [e.g. iOS] Ubuntu 20.04
 - Browser (if issue is in certain browser) [e.g. chrome, safari] safari/firefox
 - Mobile device type and version (if issue is related to TRASA mobile app) iOS (iPhone)

I also tried to use latest apache guacd  version, but I have the same problem with it.

**Comment by bhrg3se** [comment]
I can't seem to replicate this, have you passed any extra parameters while starting trasa in docker?
Also can you make sure RDP can be accessed successfully from other client?

**Comment by jsisaev1** [comment]
> I can't seem to replicate this, have you passed any extra parameters while starting trasa in docker?
> Also can you make sure RDP can be accessed successfully from other client?

I fixed this error.
Cyrillic symbols in username causes this error.
In Russian language default username is администратор. When I created admin user with Latin symbols, issue resolved.

**Comment by jsisaev1** [comment]
Also I can tell that guacamole with guacd correctly processing Cyrillic symbols in username.
