### ISSUE TITLE
[BUG] RDP not recording anything

### ISSUE THREAD

**Issue by udee297** [seknox/trasa#300]
**Describe the bug:**

RDP session didnt write anything to /tmp/trasa/accessproxy/guac/ folder

**Expected behavior:**

write log to /tmp/trasa/accessproxy/guac/

**Log file / Code snippet / Screenshots:**

could not delete guac file: remove /tmp/trasa/accessproxy/guac/119043a2-5e90-4343-b218-37cac5982a49.guac: no such file or directory" func=github.com/seknox/trasa/server/accessproxy/rdpproxy.GWStore.uploadSessionLog file="rdpproxy/store.go:45"

**Scope of issue:**

- [ ] TRASA codebase
- [ x ] dashboard
- [ x ] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
 - TRASA version 1.14
 - OS (in which TRASA is installed): [e.g. iOS]
 - Browser (if issue is in certain browser) [e.g. chrome, safari]
 - Mobile device type and version (if issue is related to TRASA mobile app)

**Additional context:**

**Comment by bhrg3se** [comment]
The file will be moved to /var/trasa/sessions once the RDP session is closed. Have you checked there ?
BTW, which version of guacd are you using?

**Comment by udee297** [comment]
hi,
im using 0.01 guacd and then i tried to 1.3.0 latest

**Comment by udee297** [comment]
> The file will be moved to /var/trasa/sessions once the RDP session is closed. Have you checked there ?
> BTW, which version of guacd are you using?

only trasa-ssh-logs exist there

**Comment by udee297** [comment]
my RDP session wont logging

this is trasa log
time=“2021-08-13T10:34:46+07:00” level=error msg=“could not delete guac file: remove /tmp/trasa/accessproxy/guac/094d4b34-5548-4c1f-8b21-a7d4478b7bf0.guac: no such file or directory” func=github.com/seknox/trasa/server/accessproxy/rdpproxy.GWStore.uploadSessionLog file=“rdpproxy/store.go:45”
time=“2021-08-13T10:34:46+07:00” level=error msg=“could not convert m4v file to mp4. ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)\n configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n libavutil 56. 31.100 / 56. 31.100\n libavcodec 58. 54.100 / 58. 54.100\n libavformat 58. 29.100 / 58. 29.100\n libavdevice 58. 8.100 / 58. 8.100\n libavfilter 7. 57.100 / 7. 57.100\n libavresample 4. 0. 0 / 4. 0. 0\n libswscale 5. 5.100 / 5. 5.100\n libswresample 3. 5.100 / 3. 5.100\n libpostproc 55. 5.100 / 55. 5.100\n/tmp/trasa/accessproxy/guac/094d4b34-5548-4c1f-8b21-a7d4478b7bf0.guac.m4v: No such file or directory\n: exit status 1” func=github.com/seknox/trasa/server/accessproxy/rdpproxy.logSession file=“rdpproxy/newguac.go:120”

im using guacd docker… was using 0.0.1 but i tried to lates still have same problem
this is docker logs
guacd[7]: INFO: Guacamole proxy daemon (guacd) version 1.3.0 started
guacd[7]: INFO: Listening on host 0.0.0.0, port 4822
guacd[7]: INFO: Creating new client for protocol “rdp”
guacd[7]: INFO: Connection ID is “$b95e7674-2af3-4dfb-9f02-9e979eacf28e”
guacd[9]: INFO: Security mode: NLA
guacd[9]: INFO: Resize method: none
guacd[9]: INFO: User “@63e7294a-73f8-4d65-907b-30ec2af98435” joined connection “$b95e7674-2af3-4dfb-9f02-9e979eacf28e” (1 users now present)
guacd[9]: ERROR: Unable to create directory “/tmp/trasa/accessproxy/guac/shared/6f80735f-c189-4697-ace9-f9216f523611”: Permission denied
guacd[9]: ERROR: Creation of recording failed: Permission denied
guacd[9]: INFO: Loading keymap “base”
guacd[9]: INFO: Loading keymap “en-us-qwerty”
guacd[9]: INFO: Connected to RDPDR 1.13 as client 0x0003
guacd[9]: INFO: Connected to RDPDR 1.13 as client 0x0002
guacd[9]: INFO: RDPDR user logged on
guacd[9]: ERROR: File open refused (-2): “”
guacd[9]: ERROR: File open refused (-2): “”
guacd[9]: ERROR: File open refused (-2): “”
guacd[9]: INFO: User “@63e7294a-73f8-4d65-907b-30ec2af98435” disconnected (0 users remain)
guacd[9]: INFO: Last user of connection “$b95e7674-2af3-4dfb-9f02-9e979eacf28e” disconnected
guacd[9]: INFO: Internal RDP client disconnected
guacd[7]: INFO: Connection “$b95e7674-2af3-4dfb-9f02-9e979eacf28e” removed.

**Comment by bhrg3se** [comment]
> ERROR: Creation of recording failed: Permission denied

You may need to run the services with "sudo"

**Comment by udee297** [comment]
> > ERROR: Creation of recording failed: Permission denied
> 
> You may need to run the services with "sudo"

Its inside docker.. how to change ? 
Im using guacd docker

**Comment by udee297** [comment]
i fixed it haha thanks @bhrg3se
