### ISSUE TITLE
[BUG] XRDP not working

### ISSUE THREAD

**Issue by lapd-viosoft** [seknox/trasa#302]
**Describe the bug:**

Currently, VNC is not supported yet to remote connect to Linux machine (with GUI). 

A workaround (possible? I'm not sure) to have desktop remote to Linux machine is installing XRDP on linux VM as XRDP is a free and open-source implementation of Microsoft RDP (Remote Desktop Protocol) server.

However, when trying to connect to this machine with Trasa, I got invalid **Invalid credentials**

**Expected behavior:**

Success to remote Linux machine with XRDP installed.

**Log file / Code snippet / Screenshots:**

If applicable, add logfile or code snippets or screenshots to help explain your problem.

**Scope of issue:**

- [ ] TRASA codebase
- [ ] dashboard
- [ ] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Versions:**
 - TRASA version
 - OS (in which TRASA is installed): [e.g. iOS]
 - Browser (if issue is in certain browser) [e.g. chrome, safari]
 - Mobile device type and version (if issue is related to TRASA mobile app)

**Additional context:**

**Comment by lapd-viosoft** [comment]
I found the reason. The RdpProtocol is not set correctly, it is set to default "nla" which seem not supported by XRDP.
After (modify TRASA source code, just quick fix to see if it work) setting default RdpProtocol to tls, it works OK now.

**Comment by bhrg3se** [comment]
But you don't need to modify the source code. You can select the RDP Protocol in service setting.
Anyway, I am closing this issue.
