### ISSUE TITLE
[FEATURE] Forced change password in first time admin login

### ISSUE THREAD

**Issue by sshahcodes** [seknox/trasa#80]
**Describe the feature:**

Currently, we do not force the admin to change default password in first login. While they can change it manually from account menu at `my` page, we should enforce change password in first time login.  

**Describe why this feature is needed:**
This feature will make root account password strong by default.

**Scope of the feature:**

- [ ] TRASA codebase
- [x] dashboard
- [x] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Comment by bhrg3se** [comment]
This is a duplicate of #65
