### ISSUE TITLE
[FEATURE] Enable autocert by default

### ISSUE THREAD

**Issue by sshahcodes** [seknox/trasa#82]
**Describe the feature:**

Fetching TLS certificate from Let's Encrypt using autocert depends on config flag `autocert`. This should be enabled by default. 

**Describe why this feature is needed:**

This will enable Let's Encrypt issued TLS certificate by default. 

**Scope of the feature:**

- [ ] TRASA codebase
- [ ] dashboard
- [x] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Comment by ByGreez** [comment]
Hello! I would like to work on this.

**Comment by ByGreez** [comment]
@bhrg3se, can u please add "hacktoberfest-accepted" label to the PR.
